---
name: ci

on:
  push:
    branches:
      - "main"

env:
  DOCKERHUB_SLUG: beholdenkey/kubedoom
  GHCR_SLUG: ghcr.io/beholdenkey/kubedoom

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo rm -rf /usr/share/dotnet
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker Tags
        id: tags
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const tags = ["latest", "v${{ github.run_number }}"];
            return tags.join(os.EOL);
      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_SLUG }}, ${{ env.GHCR_SLUG }}
          tags: ${{ steps.tags.outputs.result }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          sbom: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
