---
name: Build and Push Kubedoom

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  DOCKERHUB_SLUG: beholdenkey/kubedoom
  GHCR_SLUG: ghcr.io/beholdenkey/kubedoom
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v4
        with:
          targets: base
          set: |
            *.platform=${{ env.PLATFORMS }}
            *.cache-from=type=gha,scope=base
            *.cache-to=type=gha,scope=base,mode=max

  build-and-push:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo rm -rf /usr/share/dotnet
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const tags = ["latest", "v${{ github.run_number }}"];
            return tags.join(os.EOL);
        id: tags
      - uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_SLUG }},${{ env.GHCR_SLUG }}
          tags: ${{ steps.tags.outputs.result }}
        id: meta
      - uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v4
        with:
          files: ./docker-bake.hcl
          targets: image
          set: |
            *.platform=${{ env.PLATFORMS }}
            *.cache-from=type=gha,scope=base
            *.push=${{ startsWith(github.ref, 'refs/tags/v') }}
